name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: گرفتن پروژه
      uses: actions/checkout@v3

    - name: نصب جاوا
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: دادن دسترسی به gradlew
      run: chmod +x gradlew

    - name: ساخت APK ریلیز
      run: ./gradlew assembleRelease

    - name: آپلود APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
